name: Build and push docker image

on:
  push:
    branches: [ develop, main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.setvars.outputs.sha_short }}
      tag: ${{ steps.setvars.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        id: setvars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.setvars.outputs.sha_short }} .
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.setvars.outputs.sha_short }}
